/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xerus
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(245, 237, 239));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 108, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 20, 115, 27);

        jLabel2.setBackground(new java.awt.Color(254, 254, 254));
        jLabel2.setForeground(new java.awt.Color(248, 241, 241));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 60, 93, 30);

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(290, 60, 115, 30);

        jButton1.setBackground(new java.awt.Color(92, 239, 15));
        jButton1.setText("Login");
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 100, 50, 29);

        jLabel3.setForeground(new java.awt.Color(254, 242, 242));
        jLabel3.setText("New user ?   Create an account");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 290, 225, 17);

        jButton2.setBackground(new java.awt.Color(29, 133, 229));
        jButton2.setText("Signup");
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(true);
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 280, 84, 29);

        jButton3.setBackground(new java.awt.Color(254, 9, 12));
        jButton3.setForeground(new java.awt.Color(114, 96, 96));
        jButton3.setText("X");
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(true);
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 0, 20, 29);

        jLabel5.setForeground(new java.awt.Color(7, 82, 237));
        jLabel5.setText("Forgot password?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 140, 140, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/xerus/received_334818217086411.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 460, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
